## Getting started with Jupyter notebooks

### Running a cell
To execute code within a cell, select that cell and either (1) hit `Shift` and `Enter` or (2) hit the run button (the right pointing arrow) above.

In [3]:
1 + 1
2 + 2

4

If you're new to jupyter notebooks, note that only the last line of a cell prints by default when you execute that cell and that you can suppress this output with a semicolon

In [4]:
1 + 1
2 + 2;

### How to get docs for Julia functions

To get docs for a function you're not familiar with, precede it with a question mark. (This works at the REPL too!)

In [6]:
?repeat

search: repeat



```
repeat(A::AbstractArray, counts::Integer...)
```

Construct an array by repeating array `A` a given number of times in each dimension, specified by `counts`.

# Examples

```jldoctest
julia> repeat([1, 2, 3], 2)
6-element Array{Int64,1}:
 1
 2
 3
 1
 2
 3

julia> repeat([1, 2, 3], 2, 3)
6×3 Array{Int64,2}:
 1  1  1
 2  2  2
 3  3  3
 1  1  1
 2  2  2
 3  3  3
```

---

```
repeat(A::AbstractArray; inner=ntuple(x->1, ndims(A)), outer=ntuple(x->1, ndims(A)))
```

Construct an array by repeating the entries of `A`. The i-th element of `inner` specifies the number of times that the individual entries of the i-th dimension of `A` should be repeated. The i-th element of `outer` specifies the number of times that a slice along the i-th dimension of `A` should be repeated. If `inner` or `outer` are omitted, no repetition is performed.

# Examples

```jldoctest
julia> repeat(1:2, inner=2)
4-element Array{Int64,1}:
 1
 1
 2
 2

julia> repeat(1:2, outer=2)
4-element Array{Int64,1}:
 1
 2
 1
 2

julia> repeat([1 2; 3 4], inner=(2, 1), outer=(1, 3))
4×6 Array{Int64,2}:
 1  2  1  2  1  2
 1  2  1  2  1  2
 3  4  3  4  3  4
 3  4  3  4  3  4
```

---

```
repeat(s::AbstractString, r::Integer)
```

Repeat a string `r` times. This can be written as `s^r`.

See also: [`^`](@ref)

# Examples

```jldoctest
julia> repeat("ha", 3)
"hahaha"
```

---

```
repeat(c::AbstractChar, r::Integer) -> String
```

Repeat a character `r` times. This can equivalently be accomplished by calling [`c^r`](@ref ^).

# Examples

```jldoctest
julia> repeat('A', 3)
"AAA"
```


### How to use shell commands

Type `;` and then you can use shell commands. For example,

In [7]:
;ls

00. Jupyter_notebooks.ipynb
01. Getting started.ipynb
02. Strings.ipynb
03. Data structures.ipynb
04. Loops.ipynb
05. Conditionals.ipynb
06. Functions.ipynb
07. Packages.ipynb
08. Plotting.ipynb
09. Julia is fast.ipynb
10. Multiple dispatch.ipynb
10.1 Multiple dispatch.ipynb
11. Basic linear algebra.ipynb
12. Factorizations and other fun.ipynb
AutoDiff.ipynb
Exercise_solutions.ipynb
Exploring_benchmarking_and_performance.ipynb
Exploring_benchmarking_and_performance_solutions.ipynb
LICENSE.md
Local_installations.ipynb
README.md
Reduce and Parallel Prefix - JuliaBox.ipynb
Working with matrices.ipynb
calculate_pi.ipynb
calculate_pi_solution.ipynb
compressing_an_image.ipynb
compressing_an_image_solutions.ipynb
create_a_caesar_cipher.ipynb
create_a_caesar_cipher_solutions.ipynb
derfunc.gif
images
short-version


In [8]:
;pwd

/Users/weheng/Documents/workplace/JuliaBoxTutorials/intro-to-julia


Shell commands also work at the REPL!

In [9]:
repeat([1 2; 3 4], inner=(2, 1), outer=(1, 3))

4×6 Array{Int64,2}:
 1  2  1  2  1  2
 1  2  1  2  1  2
 3  4  3  4  3  4
 3  4  3  4  3  4